SEND_MORE = 'SHOW_MORE'
ADD_TO_FAV = 'ADD_TO_FAV'
VIEW_FAV = 'VIEW_FAV'
AUTHOR_BTN = 'AUTHOR'
POEMS_BY_AUTHOR = 'POEMS_BY_AUTHOR'
POEM_BY_NAME = 'POEM_BY_NAME'

BUTTON_BACK_IN_PLACE = 'IN_PLACE_BACK'

SECRET_LEVEL_BUTTON = 'SCRT_LVL'
CONFIRM_DECLINE_BROADCAST = 'CNFM_DCLN_BRDCST'
CONFIRM_BROADCAST = 'CONFIRM'
DECLINE_BROADCAST = 'DECLINE'